packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  msgpackr-extract: true
  msw: true

patchedDependencies:
  '@expo/cli@0.22.28': patches/@expo__cli@0.22.28.patch
