import { ROUTES } from '@/router/paths';

import { edge, L, type Flow } from './systemMap.types';

/** End-to-end: one customer visit, from sign-up to the numbers landing in reports. */
export const overviewFlow: Flow = {
  id: 'overview',
  group: 'overview',
  title: L('ພາບລວມທັງລະບົບ', 'End-to-End Overview'),
  summary: L(
    'ເສັ້ນທາງຂອງລູກຄ້າໜຶ່ງຄົນ: ລົງທະບຽນ → ຈອງ → ເຊັກອິນ → ຮັບບໍລິການ → ຊຳລະ → ກະທົບຍອດ → ລາຍງານ',
    'One customer visit: sign up → book → check in → treatment → pay → reconcile → report',
  ),
  nodes: [
    {
      id: 'c-register', lane: 'customer', col: 0,
      title: L('ລົງທະບຽນ / ເຂົ້າສູ່ລະບົບ', 'Register / Login'),
      desc: L('ລູກຄ້າສ້າງບັນຊີດ້ວຍເບີໂທ (020…) ຫຼື ເຂົ້າສູ່ລະບົບ; ຮອງຮັບ 2FA.', 'Customer signs up with a phone number (020…) or logs in; 2FA supported.'),
      apis: ['POST /auth/register', 'POST /auth/login'],
      screen: 'RegisterScreen · LoginScreen',
    },
    {
      id: 'c-browse', lane: 'customer', col: 1,
      title: L('ເລືອກບໍລິການ', 'Browse Services'),
      desc: L('ຄົ້ນຫາບໍລິການ, ເບິ່ງລາຄາ, ຄະແນນ ແລະ ແພັກເກັດທີ່ກ່ຽວຂ້ອງ.', 'Search services, prices, ratings and related packages.'),
      apis: ['GET /catalog/services', 'GET /catalog/services/:id', 'GET /pricing/promotions'],
      screen: 'ServiceListScreen · ServiceDetailScreen',
    },
    {
      id: 'c-book', lane: 'customer', col: 2,
      title: L('ຈອງຄິວ', 'Book Appointment'),
      desc: L('ເລືອກສາຂາ, ວັນ-ເວລາ ແລະ ພະນັກງານ; ລະບົບກວດຊ່ອງວ່າງ ແລະ ກັນການຈອງຊ້ອນ.', 'Pick branch, slot and staff; the server checks availability and blocks double-booking.'),
      apis: ['GET /booking/availability', 'POST /booking/appointments'],
      screen: 'WizardServiceScreen → WizardDateTimeScreen → WizardConfirmScreen',
      statuses: ['PENDING'],
    },
    {
      id: 'c-deposit', lane: 'customer', col: 3,
      title: L('ຈ່າຍມັດຈຳ QR', 'Pay Deposit (QR)'),
      desc: L('ສ້າງ QR ມັດຈຳຜ່ານ BCEL One ຫຼື ອັບໂຫຼດສະລິບໂອນ.', 'Generate a BCEL One deposit QR or upload a transfer slip.'),
      apis: ['POST /payments/:id/deposit-intent', 'POST /payments-treasury/payments/:id/slips'],
      screen: 'PaymentScreen',
      statuses: ['DEPOSIT_PAID'],
    },
    {
      id: 'c-checkin', lane: 'customer', col: 5,
      title: L('ສະແກນ QR ເຊັກອິນ', 'QR Check-in'),
      desc: L('ມາຮອດສາຂາ ສະແກນ QR ຂອງສາຂາ ເພື່ອເຂົ້າຄິວ (ພາຍໃນໄລຍະເວລາທີ່ກຳນົດ).', 'At the branch, scan the branch QR to join the queue (within the check-in window).'),
      apis: ['POST /queue/check-in'],
      screen: 'CheckInScreen',
      statuses: ['WAITING'],
    },
    {
      id: 'c-review', lane: 'customer', col: 9,
      title: L('ໃຫ້ຄະແນນ + ຮັບແຕ້ມ', 'Review + Earn Points'),
      desc: L('ຫຼັງບໍລິການ ລູກຄ້າໃຫ້ຄະແນນ; ແຕ້ມສະສົມເຂົ້າບັນຊີ loyalty ອັດຕະໂນມັດ.', 'After the visit the customer rates it; loyalty points are credited automatically.'),
      apis: ['POST /booking/appointments/:id/review', 'GET /loyalty/me'],
      screen: 'AppointmentDetailScreen · LoyaltyScreen',
    },
    {
      id: 's-today', lane: 'staff', col: 5,
      title: L('ຕາຕະລາງມື້ນີ້', 'Today Schedule'),
      desc: L('ພະນັກງານເຫັນຄິວຂອງຕົນ, ເຊັກອິນເຂົ້າວຽກ ແລະ ເລີ່ມບໍລິການ.', 'Staff see their bookings, clock in and start treatments.'),
      apis: ['GET /staff-portal/schedule', 'POST /staff-portal/attendance/check-in'],
      screen: 'StaffTodayScreen',
    },
    {
      id: 's-treat', lane: 'staff', col: 6,
      title: L('ບັນທຶກການປິ່ນປົວ', 'Treatment Record'),
      desc: L('ບັນທຶກລາຍລະອຽດ, ຮູບກ່ອນ/ຫຼັງ ແລະ ປິດງານ (COMPLETED).', 'Record notes and before/after photos, then complete the appointment.'),
      apis: ['PUT /staff-portal/appointments/:id/treatment', 'PATCH /staff-portal/appointments/:id/status'],
      screen: 'TreatmentRecordScreen',
      statuses: ['IN_PROGRESS', 'COMPLETED'],
    },
    {
      id: 'a-confirm', lane: 'admin', col: 3.5, row: 1,
      title: L('ຢືນຢັນການຈອງ', 'Confirm Booking'),
      desc: L('ແອັດມິນກວດ ແລະ ຢືນຢັນຄິວ, ປ່ຽນເວລາ ຫຼື ຍົກເລີກ.', 'Admin confirms, reschedules or cancels the booking.'),
      apis: ['PATCH /appointments/:id/status', 'POST /appointments/bulk-status'],
      route: ROUTES.appointments,
      statuses: ['CONFIRMED'],
      permission: 'appointments:manage',
    },
    {
      id: 'a-queue', lane: 'admin', col: 5.5,
      title: L('ກະດານຄິວ', 'Queue Board'),
      desc: L('ໜ້າຮ້ານເອີ້ນຄິວ, ຈັດພະນັກງານ/ຫ້ອງ ແລະ ຮັບ walk-in.', 'Front desk calls tickets, assigns staff/rooms and takes walk-ins.'),
      apis: ['GET /queue', 'PATCH /queue/:id', 'POST /appointments/walk-in'],
      route: ROUTES.queue,
      statuses: ['CALLED', 'IN_SERVICE'],
      permission: 'queue:manage',
    },
    {
      id: 'a-pos', lane: 'admin', col: 7,
      title: L('ຮັບຊຳລະ (POS)', 'Record Payment'),
      desc: L('ຮັບເງິນສົດ/QR/ບັດ/ບັດຂອງຂວັນ/ແພັກເກັດ/ແຕ້ມ; ອອກໃບບິນ INV + VAT.', 'Take cash/QR/card/gift card/package/points; issue INV receipt with VAT.'),
      apis: ['POST /payments/:id/tenders', 'GET /payments/:id/receipt'],
      route: ROUTES.finance,
      statuses: ['FULLY_PAID'],
      permission: 'finance:view',
    },
    {
      id: 'a-slips', lane: 'admin', col: 8, row: 1,
      title: L('ກວດສະລິບ', 'Slip Review'),
      desc: L('ສະລິບທີ່ OCR ບໍ່ໝັ້ນໃຈ ຖືກສົ່ງມາໃຫ້ຄົນກວດ.', 'Low-confidence OCR slips land here for human review.'),
      apis: ['GET /payments-treasury/slips', 'POST /payments-treasury/slips/:id/review'],
      route: ROUTES.paymentsSlips,
      permission: 'payments:review',
    },
    {
      id: 'a-recon', lane: 'admin', col: 9, row: 1,
      title: L('ກະທົບຍອດທະນາຄານ', 'Bank Reconciliation'),
      desc: L('ນຳເຂົ້າ statement, ຈັບຄູ່ກັບລາຍຮັບ ແລະ ລັອກງວດ.', 'Import statements, match against takings and lock the period.'),
      apis: ['POST /payments-treasury/reconciliation/imports', 'POST /payments-treasury/reconciliation/periods'],
      route: ROUTES.paymentsReconciliation,
      permission: 'payments:manage',
    },
    {
      id: 'a-reports', lane: 'admin', col: 10,
      title: L('ແດຊບອດ + ລາຍງານ', 'Dashboard + Reports'),
      desc: L('ລາຍຮັບ, ການຈອງ, ສະຕັອກ ແລະ ລາຍງານປິດມື້.', 'Revenue, bookings, stock and end-of-day statements.'),
      apis: ['GET /dashboard/stats', 'GET /reports/end-of-day'],
      route: ROUTES.dashboard,
      permission: 'dashboard:view',
    },
    {
      id: 'y-avail', lane: 'system', col: 2,
      title: L('ເຄື່ອງຄິດໄລ່ຊ່ອງວ່າງ', 'Availability Engine'),
      desc: L('ລວມເວລາເປີດສາຂາ, ວັນປິດ, ຕາຕະລາງພະນັກງານ, ຫ້ອງ/ອຸປະກອນ (ເວລາ Vientiane).', 'Combines branch hours, closures, rosters, rooms/equipment (Vientiane time).'),
      apis: ['GET /booking/availability', 'GET /pricing/quote'],
    },
    {
      id: 'y-remind', lane: 'system', col: 4,
      title: L('ແຈ້ງເຕືອນກ່ອນນັດ', 'Reminder Sweep'),
      desc: L('ທຸກ 15 ນາທີ ສົ່ງແຈ້ງເຕືອນກ່ອນເຖິງເວລານັດ.', 'Every 15 minutes, sends pre-appointment reminders.'),
      job: 'reminder.job · */15 * * * *',
    },
    {
      id: 'y-stock', lane: 'system', col: 7, row: 1,
      title: L('ຕັດສະຕັອກ FEFO', 'Stock Consumption (FEFO)'),
      desc: L('ປິດງານ → ຕັດວັດຖຸດິບຕາມສູດບໍລິການ ຈາກ lot ທີ່ໃກ້ໝົດອາຍຸກ່ອນ; ຄິດຕົ້ນທຶນ WAC.', 'On completion, deducts service consumables from the earliest-expiring lot; WAC costing.'),
      statuses: ['SERVICE_CONSUMED'],
    },
    {
      id: 'y-loyalty', lane: 'system', col: 8.5,
      title: L('ສະສົມແຕ້ມ + ຄອມມິດຊັນ', 'Points + Commission'),
      desc: L('ຊຳລະຄົບ → ບັນທຶກແຕ້ມ (EARN) ແລະ ຄອມມິດຊັນພະນັກງານ.', 'Full payment posts loyalty EARN and staff commission.'),
      statuses: ['EARN'],
    },
    {
      id: 'x-bank', lane: 'external', col: 3,
      title: L('BCEL One / ທະນາຄານ', 'BCEL One / Bank'),
      desc: L('QR ຈ່າຍເງິນ ແລະ webhook ຢືນຢັນການໂອນ.', 'QR payment and transfer-confirmation webhook.'),
      apis: ['POST /payments/webhooks/:code'],
    },
    {
      id: 'x-push', lane: 'external', col: 4.5,
      title: L('Push / LINE / SMS', 'Push / LINE / SMS'),
      desc: L('ຊ່ອງທາງສົ່ງແຈ້ງເຕືອນ (Expo push, LINE, SMS, Telegram).', 'Notification channels (Expo push, LINE, SMS, Telegram).'),
    },
  ],
  edges: [
    edge('c-register', 'c-browse', 'data'),
    edge('c-browse', 'c-book', 'data'),
    edge('c-book', 'y-avail', 'data', L('ກວດຊ່ອງວ່າງ', 'check slot')),
    edge('c-book', 'c-deposit', 'status', L('PENDING', 'PENDING')),
    edge('c-deposit', 'x-bank', 'data', L('QR intent', 'QR intent')),
    edge('x-bank', 'a-confirm', 'auto', L('webhook → DEPOSIT_PAID', 'webhook → DEPOSIT_PAID')),
    edge('a-confirm', 'y-remind', 'status', L('CONFIRMED', 'CONFIRMED')),
    edge('y-remind', 'x-push', 'auto', L('ແຈ້ງເຕືອນ', 'notify')),
    edge('c-checkin', 'a-queue', 'data', L('ticket WAITING', 'ticket WAITING')),
    edge('a-queue', 's-today', 'status', L('ເອີ້ນຄິວ', 'call')),
    edge('s-today', 's-treat', 'status', L('IN_PROGRESS', 'IN_PROGRESS')),
    edge('s-treat', 'y-stock', 'auto', L('COMPLETED', 'COMPLETED')),
    edge('s-treat', 'a-pos', 'data', L('ຍອດຄ້າງຊຳລະ', 'balance due')),
    edge('a-pos', 'y-loyalty', 'auto', L('FULLY_PAID', 'FULLY_PAID')),
    edge('a-pos', 'a-slips', 'data', L('ສະລິບໂອນ', 'transfer slip')),
    edge('y-loyalty', 'c-review', 'auto'),
    edge('a-slips', 'a-recon', 'data'),
    edge('a-recon', 'a-reports', 'data'),
  ],
};

export const authFlow: Flow = {
  id: 'auth',
  group: 'module',
  title: L('ບັນຊີ ແລະ ຄວາມປອດໄພ', 'Accounts & Security'),
  summary: L('ລົງທະບຽນ, ເຂົ້າສູ່ລະບົບ, 2FA, session, PIN ດ່ວນ ແລະ ຣີເຊັດລະຫັດ', 'Sign-up, login, 2FA, sessions, quick-login PIN and password reset'),
  nodes: [
    {
      id: 'c-reg', lane: 'customer', col: 0,
      title: L('ລົງທະບຽນ', 'Register'),
      desc: L('ເບີໂທຖືກປັບເປັນຮູບແບບ 020 ມາດຕະຖານ; ຍອມຮັບເງື່ອນໄຂ.', 'Phone normalised to the 020 format; terms accepted.'),
      apis: ['POST /auth/register'],
      screen: 'RegisterScreen',
    },
    {
      id: 'c-login', lane: 'customer', col: 1,
      title: L('ເຂົ້າສູ່ລະບົບ', 'Login'),
      desc: L('ລະຫັດຜ່ານຜິດຫຼາຍຄັ້ງ → ລັອກບັນຊີຊົ່ວຄາວ.', 'Repeated wrong passwords temporarily lock the account.'),
      apis: ['POST /auth/login', 'POST /auth/refresh'],
      screen: 'LoginScreen',
    },
    {
      id: 'c-2fa', lane: 'customer', col: 2,
      title: L('ຢືນຢັນ 2FA', 'Verify 2FA'),
      desc: L('ຖ້າເປີດ TOTP ຕ້ອງໃສ່ລະຫັດ 6 ຫຼັກ ຫຼື recovery code.', 'With TOTP enabled, enter the 6-digit code or a recovery code.'),
      apis: ['POST /auth/2fa/verify'],
      screen: 'TwoFactorScreen',
    },
    {
      id: 'c-forgot', lane: 'customer', col: 1, row: 1,
      title: L('ລືມລະຫັດຜ່ານ', 'Forgot Password'),
      desc: L('ຂໍລິ້ງຣີເຊັດ ແລ້ວຕັ້ງລະຫັດໃໝ່ (ທຸກ session ເກົ່າຖືກຍົກເລີກ).', 'Request a reset link and set a new password (old sessions revoked).'),
      apis: ['POST /auth/password/forgot', 'POST /auth/password/reset'],
      screen: 'ForgotPasswordScreen',
    },
    {
      id: 'a-account', lane: 'admin', col: 3,
      title: L('ບັນຊີຂອງຂ້ອຍ', 'My Account'),
      desc: L('ເປີດ/ປິດ 2FA, ເບິ່ງອຸປະກອນທີ່ເຂົ້າໃຊ້, ຍົກເລີກ session ອື່ນ, ຕັ້ງ PIN.', 'Toggle 2FA, view devices, revoke other sessions, set PIN.'),
      apis: ['GET /auth/me/overview', 'GET /auth/me/sessions', 'POST /auth/me/2fa/enable', 'PUT /auth/me/quick-login-pin'],
      route: ROUTES.account,
    },
    {
      id: 'a-users', lane: 'admin', col: 4,
      title: L('ຈັດການຜູ້ໃຊ້', 'User Management'),
      desc: L('ສ້າງບັນຊີ, ກຳນົດບົດບາດ/ສາຂາ, ປົດລັອກ, ຣີເຊັດລະຫັດ, ຖອນ 2FA.', 'Create accounts, set role/branch, unlock, reset password, remove 2FA.'),
      apis: ['GET /users', 'POST /users', 'POST /users/:id/unlock', 'POST /users/:id/password-reset'],
      route: ROUTES.usersRoles,
      permission: 'users:manage',
    },
    {
      id: 'a-perms', lane: 'admin', col: 5,
      title: L('ສິດເຂົ້າໃຊ້', 'Permissions'),
      desc: L('ສິດຕາມບົດບາດ + override ລາຍບຸກຄົນ.', 'Role permissions plus per-user overrides.'),
      apis: ['GET /roles', 'PUT /users/:id/permissions'],
      route: ROUTES.userPermissions,
      permission: 'users:manage',
    },
    {
      id: 'a-quick', lane: 'admin', col: 5, row: 1,
      title: L('Quick Login (PIN)', 'Quick Login (PIN)'),
      desc: L('PIN ສຳລັບເຄື່ອງໜ້າຮ້ານທີ່ໃຊ້ຮ່ວມກັນ.', 'PIN login for shared front-desk devices.'),
      apis: ['POST /auth/quick-login', 'POST /users/:id/quick-login'],
      route: ROUTES.quickLoginManagement,
      permission: 'users:manage',
    },
    {
      id: 'y-session', lane: 'system', col: 2,
      title: L('UserSession + JWT sid', 'UserSession + JWT sid'),
      desc: L('ທຸກ token ຜູກກັບ session; ໝົດເວລາບໍ່ເຄື່ອນໄຫວ → ອອກອັດຕະໂນມັດ.', 'Every token is bound to a session; idle timeout signs out.'),
    },
    {
      id: 'y-audit', lane: 'system', col: 4.5,
      title: L('Audit Log', 'Audit Log'),
      desc: L('ທຸກການປ່ຽນແປງຜ່ານ API ຖືກບັນທຶກ (ໃຜ, ຫຍັງ, ເມື່ອໃດ).', 'Every API mutation is logged (who, what, when).'),
      route: ROUTES.auditLog,
      permission: 'settings:view',
    },
  ],
  edges: [
    edge('c-reg', 'c-login', 'data'),
    edge('c-login', 'c-2fa', 'status', L('ຕ້ອງ 2FA', '2FA required')),
    edge('c-login', 'c-forgot', 'data', L('ລືມລະຫັດ', 'forgot')),
    edge('c-2fa', 'y-session', 'data', L('ອອກ token', 'issue token')),
    edge('y-session', 'a-account', 'data'),
    edge('a-users', 'a-perms', 'data'),
    edge('a-users', 'a-quick', 'data'),
    edge('a-users', 'y-audit', 'auto'),
    edge('a-account', 'y-session', 'status', L('ຍົກເລີກ session', 'revoke')),
  ],
};

export const bookingFlow: Flow = {
  id: 'booking',
  group: 'module',
  title: L('ການຈອງ ແລະ ນັດໝາຍ', 'Booking & Appointments'),
  summary: L('ຈອງຜ່ານແອັບ/ໜ້າຮ້ານ, ມັດຈຳ, ຢືນຢັນ, ເລື່ອນ/ຍົກເລີກ, waitlist', 'App/desk booking, deposit, confirm, reschedule/cancel, waitlist'),
  nodes: [
    {
      id: 'c-service', lane: 'customer', col: 0,
      title: L('ເລືອກບໍລິການ', 'Choose Service'),
      desc: L('ຂັ້ນ 1 ຂອງ wizard: ບໍລິການ, ສາຂາ, ບັນທຶກພິເສດ.', 'Wizard step 1: service, branch, notes.'),
      apis: ['GET /catalog/services', 'GET /catalog/branches'],
      screen: 'WizardServiceScreen',
    },
    {
      id: 'c-slot', lane: 'customer', col: 1,
      title: L('ເລືອກວັນ-ເວລາ', 'Pick Date & Time'),
      desc: L('ລາຄາອາດປ່ຽນຕາມຊ່ວງເວລາ (dynamic pricing).', 'Price may change by time band (dynamic pricing).'),
      apis: ['GET /booking/availability', 'GET /pricing/quote'],
      screen: 'WizardDateTimeScreen',
    },
    {
      id: 'c-confirm', lane: 'customer', col: 2,
      title: L('ຢືນຢັນ + ວິທີຈ່າຍ', 'Confirm + Pay Method'),
      desc: L('ລູກຄ້າຈ່າຍຜ່ານ QR/ໂອນເທົ່ານັ້ນ; ເງິນສົດຮັບທີ່ໜ້າຮ້ານ.', 'Customers pay by QR/transfer only; cash is taken at the desk.'),
      apis: ['POST /booking/appointments'],
      screen: 'WizardConfirmScreen',
      statuses: ['PENDING'],
    },
    {
      id: 'c-success', lane: 'customer', col: 3,
      title: L('ບັດນັດ (Pass)', 'Appointment Pass'),
      desc: L('ສະແດງເລກນັດ, ເພີ່ມໃສ່ປະຕິທິນ, ແຊັດກັບຄລີນິກ.', 'Shows the booking code, add-to-calendar, chat with clinic.'),
      screen: 'BookingSuccessScreen',
    },
    {
      id: 'c-manage', lane: 'customer', col: 5,
      title: L('ເລື່ອນ / ຍົກເລີກ', 'Reschedule / Cancel'),
      desc: L('ອະນຸຍາດພາຍໃນໄລຍະເວລາທີ່ຕັ້ງໄວ້ໃນ Settings ເທົ່ານັ້ນ.', 'Only allowed inside the cancel window set in Settings.'),
      apis: ['PATCH /booking/appointments/:id/reschedule', 'PATCH /booking/appointments/:id/cancel', 'GET /booking/policy'],
      screen: 'AppointmentDetailScreen',
      statuses: ['CANCELLED'],
    },
    {
      id: 'c-waitlist', lane: 'customer', col: 1, row: 1,
      title: L('ລົງຊື່ລໍຖ້າ', 'Join Waitlist'),
      desc: L('ເຕັມແລ້ວ → ລໍຖ້າຊ່ອງທີ່ຖືກຍົກເລີກ.', 'Slot full → wait for a cancellation.'),
      apis: ['POST /waitlist', 'GET /waitlist/me'],
    },
    {
      id: 'a-calendar', lane: 'admin', col: 3, row: 1,
      title: L('ປະຕິທິນ', 'Calendar'),
      desc: L('ມຸມມອງວັນ/ອາທິດ ຕາມພະນັກງານ ຫຼື ຫ້ອງ; ລາກເພື່ອເລື່ອນນັດ.', 'Day/week by staff or room; drag to reschedule.'),
      apis: ['GET /appointments/calendar', 'PATCH /appointments/:id/reschedule'],
      route: ROUTES.calendar,
      permission: 'calendar:view',
    },
    {
      id: 'a-console', lane: 'admin', col: 4,
      title: L('ສູນຄວບຄຸມການນັດ', 'Appointments Console'),
      desc: L('4 ມຸມມອງ, ສະຫຼຸບຍອດ, ປ່ຽນສະຖານະຫຼາຍລາຍການພ້ອມກັນ.', '4 views, summary strip, bulk status changes.'),
      apis: ['GET /appointments', 'GET /appointments/summary', 'POST /appointments/bulk-status'],
      route: ROUTES.appointments,
      statuses: ['CONFIRMED', 'NO_SHOW'],
      permission: 'appointments:manage',
    },
    {
      id: 'a-walkin', lane: 'admin', col: 2, row: 1,
      title: L('ຈອງໜ້າຮ້ານ (Walk-in)', 'Walk-in Booking'),
      desc: L('ພະນັກງານສ້າງນັດໃຫ້ລູກຄ້າທີ່ມາເອງ.', 'Staff create a booking for a walk-in customer.'),
      apis: ['POST /appointments/walk-in'],
      route: ROUTES.appointments,
      statuses: ['WALK_IN'],
      permission: 'appointments:create',
    },
    {
      id: 'y-guard', lane: 'system', col: 2,
      title: L('ກັນຈອງຊ້ອນ', 'Double-booking Guard'),
      desc: L('ລັອກແຖວໃນ transaction ແລະ ກວດເວລາຊ້ອນ (tsParam ກັນ 7 ຊົ່ວໂມງເລື່ອນ).', 'Row lock inside a transaction plus overlap check (tsParam avoids the 7h shift).'),
    },
    {
      id: 'y-remind', lane: 'system', col: 4, row: 1,
      title: L('ແຈ້ງເຕືອນນັດ', 'Reminder Job'),
      desc: L('ສົ່ງແຈ້ງເຕືອນຕາມເວລາທີ່ຕັ້ງໃນ Settings ▸ ແຈ້ງເຕືອນ.', 'Sends reminders on the timing set in Settings ▸ Notifications.'),
      job: 'reminder.job · */15 * * * *',
      route: ROUTES.settingsNotifications,
    },
    {
      id: 'y-waitlist', lane: 'system', col: 6,
      title: L('ເຕີມຊ່ອງວ່າງ Waitlist', 'Waitlist Backfill'),
      desc: L('ມີຄົນຍົກເລີກ → ແຈ້ງຄົນທີ່ລໍຖ້າບໍລິການ/ວັນນັ້ນ.', 'On cancellation, notify people waiting for that service/day.'),
      job: 'waitlist.job · on cancel',
    },
    {
      id: 'y-expire', lane: 'system', col: 3,
      title: L('QR ໝົດອາຍຸ', 'Payment Expiry'),
      desc: L('QR ມັດຈຳທີ່ບໍ່ຈ່າຍ ຖືກໝາຍ EXPIRED ທຸກ 10 ນາທີ.', 'Unpaid deposit QRs are marked EXPIRED every 10 minutes.'),
      job: 'payment-expiry.job · */10 * * * *',
      statuses: ['EXPIRED'],
    },
    {
      id: 'x-push', lane: 'external', col: 5,
      title: L('Push / LINE / SMS', 'Push / LINE / SMS'),
      desc: L('ສົ່ງຕາມການຍິນຍອມ (consent) ຂອງລູກຄ້າ.', 'Delivered according to customer consent.'),
    },
  ],
  edges: [
    edge('c-service', 'c-slot', 'data'),
    edge('c-slot', 'c-waitlist', 'data', L('ເຕັມ', 'full')),
    edge('c-slot', 'c-confirm', 'data'),
    edge('c-confirm', 'y-guard', 'data'),
    edge('a-walkin', 'y-guard', 'data'),
    edge('y-guard', 'c-success', 'status', L('PENDING', 'PENDING')),
    edge('y-guard', 'y-expire', 'auto', L('QR intent', 'QR intent')),
    edge('c-success', 'a-console', 'data'),
    edge('a-calendar', 'a-console', 'data'),
    edge('a-console', 'y-remind', 'status', L('CONFIRMED', 'CONFIRMED')),
    edge('y-remind', 'x-push', 'auto'),
    edge('c-manage', 'y-waitlist', 'auto', L('CANCELLED', 'CANCELLED')),
    edge('y-waitlist', 'x-push', 'auto'),
    edge('c-waitlist', 'y-waitlist', 'data'),
  ],
};

export const queueFlow: Flow = {
  id: 'queue',
  group: 'module',
  title: L('ເຊັກອິນ ແລະ ຄິວໜ້າຮ້ານ', 'Check-in & Queue'),
  summary: L('QR ສາຂາ → ticket → ເອີ້ນ → ບໍລິການ → ສຳເລັດ; ຫ້ອງ ແລະ ອຸປະກອນ', 'Branch QR → ticket → call → serve → done; rooms & equipment'),
  nodes: [
    {
      id: 'a-qr', lane: 'admin', col: 0,
      title: L('QR ເຊັກອິນສາຂາ', 'Branch Check-in QR'),
      desc: L('ພິມ/ສະແດງ QR ຂອງແຕ່ລະສາຂາ ທີ່ໜ້າຮ້ານ.', 'Print/display each branch QR at the counter.'),
      route: ROUTES.branches,
      permission: 'branches:view',
    },
    {
      id: 'c-scan', lane: 'customer', col: 1,
      title: L('ສະແກນ QR', 'Scan QR'),
      desc: L('ກວດ payload + ໄລຍະເວລາເຊັກອິນ (ກ່ອນ/ຫຼັງເວລານັດ).', 'Validates payload + check-in window around the appointment time.'),
      apis: ['POST /queue/check-in'],
      screen: 'CheckInScreen',
    },
    {
      id: 'a-walk', lane: 'admin', col: 1, row: 1,
      title: L('ລູກຄ້າ Walk-in', 'Walk-in'),
      desc: L('ບໍ່ມີແອັບ → ໜ້າຮ້ານອອກ ticket ໃຫ້.', 'No app → the desk issues a ticket.'),
      apis: ['POST /appointments/walk-in'],
      route: ROUTES.queue,
    },
    {
      id: 'y-ticket', lane: 'system', col: 2,
      title: L('ອອກ Ticket', 'Issue Ticket'),
      desc: L('ເລກຄິວຕໍ່ວັນ Vientiane, ລະດັບ NORMAL/VIP.', 'Per-Vientiane-day number, NORMAL/VIP priority.'),
      statuses: ['WAITING', 'NORMAL', 'VIP'],
    },
    {
      id: 'a-board', lane: 'admin', col: 3,
      title: L('ກະດານຄິວ', 'Queue Board'),
      desc: L('ເອີ້ນ, ເອີ້ນຊ້ຳ, ປ່ຽນລາຍລະອຽດ, ລ້າງ ticket ຄ້າງ.', 'Call, recall, edit details, clear stale tickets.'),
      apis: ['GET /queue', 'PATCH /queue/:id', 'POST /queue/:id/recall', 'POST /queue/clear-stale'],
      route: ROUTES.queue,
      statuses: ['CALLED'],
      permission: 'queue:manage',
    },
    {
      id: 'a-rooms', lane: 'admin', col: 4, row: 1,
      title: L('ຫ້ອງ ແລະ ອຸປະກອນ', 'Rooms & Equipment'),
      desc: L('ຈັດສັນຊັບພະຍາກອນ; ບໍລິການທີ່ຕ້ອງໃຊ້ຫ້ອງ/ເຄື່ອງ ຈະຖືກກັນໄວ້.', 'Resource allocation; services that need a room/device reserve it.'),
      apis: ['GET /resources/rooms', 'GET /resources/equipment'],
      route: ROUTES.resources,
      permission: 'queue:manage',
    },
    {
      id: 's-serve', lane: 'staff', col: 4,
      title: L('ເລີ່ມບໍລິການ', 'Start Service'),
      desc: L('ພະນັກງານກົດເລີ່ມ → ticket IN_SERVICE, ນັດ IN_PROGRESS.', 'Staff taps start → ticket IN_SERVICE, appointment IN_PROGRESS.'),
      apis: ['PATCH /staff-portal/appointments/:id/status'],
      screen: 'StaffTodayScreen',
      statuses: ['IN_SERVICE'],
    },
    {
      id: 's-done', lane: 'staff', col: 5,
      title: L('ສຳເລັດ', 'Complete'),
      desc: L('ປິດ ticket ແລະ ນັດ; ສົ່ງຕໍ່ໄປຮັບຊຳລະ.', 'Closes ticket and appointment; hands off to payment.'),
      statuses: ['COMPLETED'],
    },
    {
      id: 'x-display', lane: 'external', col: 3,
      title: L('ຈໍສະແດງຄິວ (Socket)', 'Queue Display (Socket)'),
      desc: L('ອັບເດດແບບ realtime ຜ່ານ socket.io.', 'Realtime updates over socket.io.'),
    },
  ],
  edges: [
    edge('a-qr', 'c-scan', 'data'),
    edge('c-scan', 'y-ticket', 'data'),
    edge('a-walk', 'y-ticket', 'data'),
    edge('y-ticket', 'a-board', 'status', L('WAITING', 'WAITING')),
    edge('a-board', 'x-display', 'auto', L('CALLED', 'CALLED')),
    edge('a-board', 's-serve', 'status'),
    edge('a-rooms', 's-serve', 'data', L('ກັນຫ້ອງ', 'reserve')),
    edge('s-serve', 's-done', 'status'),
  ],
};

export const treatmentFlow: Flow = {
  id: 'treatment',
  group: 'module',
  title: L('ພະນັກງານ ແລະ ການປິ່ນປົວ', 'Staff Portal & Treatment'),
  summary: L('ເຂົ້າວຽກ, ຕາຕະລາງ, ບັນທຶກການປິ່ນປົວ, ຮູບ, ຄອມມິດຊັນ', 'Clock-in, schedule, treatment records, photos, commission'),
  nodes: [
    {
      id: 's-clock', lane: 'staff', col: 0,
      title: L('ເຊັກອິນເຂົ້າວຽກ', 'Clock In'),
      desc: L('ບັນທຶກເວລາ: ON_TIME / LATE / OVERTIME.', 'Records time: ON_TIME / LATE / OVERTIME.'),
      apis: ['POST /staff-portal/attendance/check-in', 'POST /staff-portal/attendance/check-out'],
      screen: 'StaffAttendanceScreen',
      statuses: ['ON_TIME', 'LATE', 'OVERTIME', 'ABSENT'],
    },
    {
      id: 's-today', lane: 'staff', col: 1,
      title: L('ຄິວມື້ນີ້', "Today's Queue"),
      desc: L('ບັດເນັ້ນນັດຕໍ່ໄປ + ປຸ່ມເລີ່ມ/ສຳເລັດ.', 'Hero card for the next booking + start/complete.'),
      apis: ['GET /staff-portal/schedule'],
      screen: 'StaffTodayScreen',
    },
    {
      id: 's-detail', lane: 'staff', col: 2,
      title: L('ລາຍລະອຽດລູກຄ້າ', 'Client Detail'),
      desc: L('ປະຫວັດ, ຂໍ້ຄວນລະວັງ, ການວິເຄາະຜິວ.', 'History, contraindications, skin analysis.'),
      apis: ['GET /staff-portal/appointments/:id', 'GET /skin-analysis/me'],
      screen: 'StaffAppointmentDetailScreen',
    },
    {
      id: 's-record', lane: 'staff', col: 3,
      title: L('ບັນທຶກການປິ່ນປົວ', 'Treatment Record'),
      desc: L('ບັນທຶກ, ຮູບ BEFORE/AFTER/PROGRESS, ວັດຖຸທີ່ໃຊ້.', 'Notes, BEFORE/AFTER/PROGRESS photos, materials used.'),
      apis: ['PUT /staff-portal/appointments/:id/treatment', 'POST /staff-portal/appointments/:id/treatment/photos'],
      screen: 'TreatmentRecordScreen',
      statuses: ['BEFORE', 'AFTER', 'PROGRESS'],
    },
    {
      id: 's-earn', lane: 'staff', col: 5,
      title: L('ລາຍໄດ້ຂອງຂ້ອຍ', 'My Earnings'),
      desc: L('ຄອມມິດຊັນ ແລະ KPI ຂອງເດືອນ.', 'Commission and KPI for the month.'),
      apis: ['GET /staff-portal/commission'],
      screen: 'StaffEarningsScreen',
    },
    {
      id: 'y-upload', lane: 'system', col: 3, row: 1,
      title: L('ເກັບຮູບແບບສ່ວນຕົວ', 'Private Uploads'),
      desc: L('ຮູບຢູ່ /uploads ແບບສ່ວນຕົວ; API ສົ່ງ URL ທີ່ລົງລາຍເຊັນ.', 'Photos stored privately; API returns signed URLs.'),
    },
    {
      id: 'y-complete', lane: 'system', col: 4,
      title: L('ປິດງານ', 'Completion Hooks'),
      desc: L('COMPLETED → ຕັດສະຕັອກ, ຄິດຄອມມິດຊັນ, ຂໍຄະແນນຈາກລູກຄ້າ.', 'COMPLETED → consume stock, accrue commission, ask for a review.'),
      statuses: ['COMPLETED', 'SERVICE_CONSUMED'],
    },
    {
      id: 'a-staff', lane: 'admin', col: 1, row: 1,
      title: L('ຂໍ້ມູນພະນັກງານ', 'Staff Profiles'),
      desc: L('ທັກສະ, ສາຂາ, ອັດຕາຄອມມິດຊັນ.', 'Skills, branches, commission rates.'),
      apis: ['GET /staff', 'PATCH /staff/:id'],
      route: ROUTES.staff,
      permission: 'staff:view',
    },
    {
      id: 'a-payroll', lane: 'admin', col: 5, row: 1,
      title: L('ເງິນເດືອນ + KPI', 'Payroll + KPI'),
      desc: L('ຄິດ KPI ຄືນ, ຈ່າຍຄອມມິດຊັນ/ໂບນັດ, ສົ່ງອອກ.', 'Recompute KPI, pay commission/bonus, export.'),
      apis: ['GET /payroll/kpi', 'POST /payroll/kpi/recompute', 'POST /payroll/commissions/pay-bulk'],
      route: ROUTES.payroll,
      permission: 'staff:view',
    },
  ],
  edges: [
    edge('s-clock', 's-today', 'data'),
    edge('s-today', 's-detail', 'data'),
    edge('s-detail', 's-record', 'status', L('IN_PROGRESS', 'IN_PROGRESS')),
    edge('s-record', 'y-upload', 'data', L('ຮູບ', 'photos')),
    edge('s-record', 'y-complete', 'status', L('COMPLETED', 'COMPLETED')),
    edge('y-complete', 's-earn', 'auto'),
    edge('y-complete', 'a-payroll', 'auto'),
    edge('a-staff', 's-today', 'data', L('ຕາຕະລາງ', 'roster')),
  ],
};

export const homeServiceFlow: Flow = {
  id: 'home-service',
  group: 'module',
  title: L('ບໍລິການນອກສະຖານທີ່ + GPS', 'Home Service + GPS'),
  summary: L('ຈອງບໍລິການທີ່ບ້ານ → ຈັບຄູ່ພະນັກງານ → ຕິດຕາມ GPS → ສຳເລັດ', 'Home booking → staff matching → GPS tracking → done'),
  nodes: [
    {
      id: 'c-book', lane: 'customer', col: 0,
      title: L('ຈອງບໍລິການທີ່ບ້ານ', 'Book Home Service'),
      desc: L('deliveryType = HOME_SERVICE ພ້ອມທີ່ຢູ່/ພິກັດ.', 'deliveryType = HOME_SERVICE with address/coordinates.'),
      apis: ['POST /booking/appointments'],
      statuses: ['HOME_SERVICE'],
    },
    {
      id: 'y-match', lane: 'system', col: 1,
      title: L('ຈັບຄູ່ພະນັກງານ', 'Staff Matching'),
      desc: L('ຫາພະນັກງານທີ່ວ່າງ ແລະ ເປີດຮັບງານນອກ.', 'Finds available staff who accept home jobs.'),
      statuses: ['MATCHING', 'NO_MATCH'],
    },
    {
      id: 'a-dispatch', lane: 'admin', col: 2,
      title: L('ສູນສົ່ງງານ', 'Dispatch Console'),
      desc: L('ແຜນທີ່ MapLibre + OSM, ມອບງານດ້ວຍມື.', 'MapLibre + OSM map, manual assignment.'),
      apis: ['GET /home-service/admin/trips', 'PATCH /home-service/admin/trips/:appointmentId/assign'],
      route: ROUTES.homeServiceDispatch,
      statuses: ['ASSIGNED'],
      permission: 'queue:manage',
    },
    {
      id: 's-avail', lane: 'staff', col: 1,
      title: L('ເປີດຮັບງານນອກ', 'Toggle Availability'),
      desc: L('ພະນັກງານເປີດ/ປິດ ການຮັບງານນອກສະຖານທີ່.', 'Staff switch home-job availability on/off.'),
      apis: ['PATCH /home-service/staff/availability'],
    },
    {
      id: 's-trip', lane: 'staff', col: 3,
      title: L('ເດີນທາງ', 'Active Trip'),
      desc: L('ສົ່ງພິກັດ GPS ເປັນໄລຍະ; EN_ROUTE → ARRIVED.', 'Streams GPS; EN_ROUTE → ARRIVED.'),
      apis: ['POST /home-service/staff/location', 'PATCH /home-service/trips/:appointmentId/status'],
      screen: 'StaffActiveTripScreen',
      statuses: ['EN_ROUTE', 'ARRIVED'],
    },
    {
      id: 'c-track', lane: 'customer', col: 4,
      title: L('ຕິດຕາມພະນັກງານ', 'Track Staff'),
      desc: L('ເຫັນຕຳແໜ່ງ ແລະ ເວລາມາຮອດແບບ realtime.', 'Live position and ETA.'),
      apis: ['GET /home-service/:appointmentId'],
      screen: 'HomeServiceTrackingScreen',
    },
    {
      id: 's-serve', lane: 'staff', col: 5,
      title: L('ໃຫ້ບໍລິການ', 'Serve'),
      desc: L('IN_PROGRESS → COMPLETED ແລ້ວຮັບຊຳລະ.', 'IN_PROGRESS → COMPLETED, then take payment.'),
      statuses: ['IN_PROGRESS', 'COMPLETED'],
    },
    {
      id: 'y-sla', lane: 'system', col: 3, row: 1,
      title: L('SLA ງານນອກ', 'Home-service SLA'),
      desc: L('ທຸກ 5 ນາທີ ກວດງານທີ່ຄ້າງ ແລະ ແຈ້ງແອັດມິນ.', 'Every 5 min flags stuck jobs to admins.'),
      job: 'home-service-sla.job · */5 * * * *',
    },
    {
      id: 'x-map', lane: 'external', col: 3,
      title: L('OpenStreetMap', 'OpenStreetMap'),
      desc: L('ແຜນທີ່ບໍ່ມີຄ່າໃຊ້ຈ່າຍ (ບໍ່ຕ້ອງ Google key).', 'Zero-cost map tiles (no Google key).'),
    },
  ],
  edges: [
    edge('c-book', 'y-match', 'data'),
    edge('s-avail', 'y-match', 'data'),
    edge('y-match', 'a-dispatch', 'status', L('NO_MATCH → ມອບເອງ', 'NO_MATCH → manual')),
    edge('a-dispatch', 's-trip', 'status', L('ASSIGNED', 'ASSIGNED')),
    edge('s-trip', 'c-track', 'data', L('GPS', 'GPS')),
    edge('x-map', 'c-track', 'data'),
    edge('y-sla', 'a-dispatch', 'auto', L('ແຈ້ງເຕືອນ', 'alert')),
    edge('s-trip', 's-serve', 'status'),
  ],
};
