import { ROUTES } from '@/router/paths';

import { edge, L, type Flow } from './systemMap.types';

export const paymentsFlow: Flow = {
  id: 'payments',
  group: 'module',
  title: L('ການຊຳລະເງິນ ແລະ ໃບບິນ', 'Payments & Receipts'),
  summary: L('ຫຼາຍວິທີຈ່າຍ, QR BCEL, webhook, VAT, ຄືນເງິນ, ລິ້ນຊັກເງິນສົດ', 'Split tenders, BCEL QR, webhook, VAT, refunds, cash drawer'),
  nodes: [
    {
      id: 'a-create', lane: 'admin', col: 0,
      title: L('ສ້າງລາຍການຊຳລະ', 'Create Payment'),
      desc: L('ຜູກກັບນັດ; ຄິດ VAT (INCLUSIVE/EXCLUSIVE) ຕາມການຕັ້ງຄ່າ.', 'Linked to an appointment; VAT computed per settings (INCLUSIVE/EXCLUSIVE).'),
      apis: ['POST /payments', 'GET /payments/by-appointment/:appointmentId', 'GET /payments/vat-settings'],
      route: ROUTES.finance,
      statuses: ['PENDING'],
      permission: 'finance:view',
    },
    {
      id: 'a-tender', lane: 'admin', col: 1,
      title: L('ຮັບເງິນຫຼາຍວິທີ', 'Split Tenders'),
      desc: L('CASH, BCEL_ONE_QR, CREDIT_CARD, GIFT_CARD, PACKAGE_CREDIT, LOYALTY_POINTS, BANK_TRANSFER.', 'CASH, BCEL_ONE_QR, CREDIT_CARD, GIFT_CARD, PACKAGE_CREDIT, LOYALTY_POINTS, BANK_TRANSFER.'),
      apis: ['POST /payments/:id/tenders'],
      route: ROUTES.finance,
      statuses: ['CASH', 'BCEL_ONE_QR', 'GIFT_CARD', 'PACKAGE_CREDIT', 'LOYALTY_POINTS'],
      permission: 'finance:view',
    },
    {
      id: 'c-qr', lane: 'customer', col: 1,
      title: L('ຈ່າຍ QR ໃນແອັບ', 'Pay QR in App'),
      desc: L('ລູກຄ້າຈ່າຍມັດຈຳ/ຍອດເຫຼືອຜ່ານ QR ເທົ່ານັ້ນ.', 'Customers pay deposit/balance by QR only.'),
      apis: ['POST /payments/:id/deposit-intent', 'POST /payments-treasury/providers/:code/qr-intent'],
      screen: 'PaymentScreen',
    },
    {
      id: 'x-bcel', lane: 'external', col: 2,
      title: L('BCEL One / ທະນາຄານ', 'BCEL One / Bank'),
      desc: L('ຜູ້ໃຫ້ບໍລິການຈ່າຍເງິນ; ຢືນຢັນຜ່ານ webhook (ມີລາຍເຊັນ).', 'Payment provider; confirms via signed webhook.'),
      apis: ['POST /payments/webhooks/:code'],
      statuses: ['SUCCESS', 'EXPIRED', 'FAILED'],
    },
    {
      id: 'y-settle', lane: 'system', col: 3,
      title: L('ປິດຍອດ + ບັນຊີຄ້າງ', 'Settle + Ledger Lock'),
      desc: L('DB trigger ກັນການແກ້ລາຍການທີ່ປິດແລ້ວ; runSerializable retry.', 'DB triggers block edits to settled rows; serializable retry.'),
      statuses: ['DEPOSIT_PAID', 'FULLY_PAID'],
    },
    {
      id: 'a-receipt', lane: 'admin', col: 4,
      title: L('ໃບບິນ INV + VAT', 'INV Receipt + VAT'),
      desc: L('ເລກເອກະສານຕໍ່ເນື່ອງ INV/CN/Z; ລາຍງານ VAT.', 'Sequential INV/CN/Z numbers; VAT report.'),
      apis: ['GET /payments/:id/receipt', 'GET /payments/vat-report'],
      route: ROUTES.finance,
      permission: 'finance:view',
    },
    {
      id: 'a-refund', lane: 'admin', col: 5,
      title: L('ຄືນເງິນ (CN)', 'Refund (Credit Note)'),
      desc: L('ຂໍ → ອະນຸມັດ → ຈ່າຍ; ອອກໃບລົດໜີ້ CN.', 'Request → approve → pay; issues a CN credit note.'),
      apis: ['POST /payments/:id/refunds', 'POST /payments/refunds/:id/approve', 'POST /payments/refunds/:id/pay'],
      route: ROUTES.finance,
      statuses: ['PENDING', 'APPROVED', 'REJECTED', 'PAID'],
      permission: 'finance:view',
    },
    {
      id: 'a-void', lane: 'admin', col: 5, row: 1,
      title: L('ຍົກເລີກລາຍການ', 'Void Payment'),
      desc: L('ຍົກເລີກກ່ອນປິດງວດ; ບັນທຶກເຫດຜົນໃນ audit log.', 'Void before the period closes; reason is audited.'),
      apis: ['POST /payments/:id/void'],
      statuses: ['VOIDED'],
      permission: 'finance:view',
    },
    {
      id: 'a-drawer', lane: 'admin', col: 2, row: 1,
      title: L('ລິ້ນຊັກເງິນສົດ', 'Cash Drawer'),
      desc: L('ເປີດກະ, ນຳເງິນເຂົ້າ/ອອກ, ປິດກະ → Z-report + ສ່ວນຕ່າງ.', 'Open shift, pay-in/out, close → Z-report + variance.'),
      apis: ['POST /payments-treasury/cash-drawer/sessions', 'POST /payments-treasury/cash-drawer/sessions/:id/close', 'GET /payments-treasury/cash-drawer/sessions/:id/z-report'],
      route: ROUTES.finance,
      statuses: ['OPEN', 'CLOSED', 'DROP', 'PAYIN', 'PAYOUT'],
      permission: 'finance:view',
    },
    {
      id: 'y-post', lane: 'system', col: 4, row: 1,
      title: L('ຜົນຕໍ່ເນື່ອງ', 'Post-payment Effects'),
      desc: L('ແຕ້ມ EARN, ໃຊ້ບັດຂອງຂວັນ/ແພັກເກັດ, ຄອມມິດຊັນ, ແຈ້ງເຕືອນ.', 'Loyalty EARN, gift card/package drawdown, commission, notification.'),
    },
    {
      id: 'y-expire', lane: 'system', col: 2, row: 1,
      title: L('QR ໝົດອາຍຸ', 'Intent Expiry'),
      desc: L('ກັນການຢືນຢັນ QR ເກົ່າ.', 'Prevents stale QRs from being confirmed.'),
      job: 'payment-expiry.job · */10 * * * *',
    },
  ],
  edges: [
    edge('a-create', 'a-tender', 'data'),
    edge('a-create', 'c-qr', 'data', L('ລິ້ງຈ່າຍ', 'pay link')),
    edge('c-qr', 'x-bcel', 'data', L('QR intent', 'QR intent')),
    edge('a-tender', 'x-bcel', 'data'),
    edge('x-bcel', 'y-settle', 'auto', L('webhook SUCCESS', 'webhook SUCCESS')),
    edge('x-bcel', 'y-expire', 'auto', L('ບໍ່ຈ່າຍ', 'unpaid')),
    edge('a-tender', 'a-drawer', 'data', L('CASH', 'CASH')),
    edge('y-settle', 'a-receipt', 'status', L('FULLY_PAID', 'FULLY_PAID')),
    edge('y-settle', 'y-post', 'auto'),
    edge('a-receipt', 'a-refund', 'status'),
    edge('a-receipt', 'a-void', 'status'),
  ],
};

export const slipsFlow: Flow = {
  id: 'slips',
  group: 'module',
  title: L('ສະລິບໂອນ + OCR', 'Transfer Slips + OCR'),
  summary: L('ອັບໂຫຼດ → OCR → ຈັບຄູ່ອັດຕະໂນມັດ / ຄົນກວດ → ອະນຸມັດ ຫຼື ປະຕິເສດ', 'Upload → OCR → auto-match / human review → approve or reject'),
  nodes: [
    {
      id: 'c-upload', lane: 'customer', col: 0,
      title: L('ອັບໂຫຼດສະລິບ', 'Upload Slip'),
      desc: L('ລູກຄ້າ ຫຼື ພະນັກງານ ແນບຮູບສະລິບ ກັບລາຍການຊຳລະ.', 'Customer or staff attaches a slip image to a payment.'),
      apis: ['POST /payments-treasury/payments/:id/slips'],
      screen: 'PaymentScreen',
    },
    {
      id: 's-upload', lane: 'staff', col: 0,
      title: L('ພະນັກງານອັບໂຫຼດ', 'Staff Upload'),
      desc: L('ຮັບສະລິບແທນລູກຄ້າທີ່ໜ້າຮ້ານ.', 'Upload on behalf of a customer at the desk.'),
      screen: 'StaffSlipInboxScreen',
    },
    {
      id: 'y-ocr', lane: 'system', col: 1,
      title: L('OCR ສະລິບ', 'Slip OCR'),
      desc: L('ອ່ານຈຳນວນເງິນ, ວັນທີ, ເລກອ້າງອີງ, ບັນຊີຜູ້ຮັບ.', 'Reads amount, date, reference, receiving account.'),
      job: 'slip-ocr.job · on upload',
      statuses: ['PENDING', 'PROCESSING', 'DONE', 'FAILED'],
    },
    {
      id: 'y-risk', lane: 'system', col: 2,
      title: L('ສັນຍານຄວາມສ່ຽງ', 'Risk Signals'),
      desc: L('ກວດຊ້ຳ (DUPLICATE), ບັນຊີຜູ້ຮັບບໍ່ກົງ, ຍອດບໍ່ກົງ, ວັນທີເກົ່າ.', 'Duplicate check, wrong receiving account, amount mismatch, stale date.'),
    },
    {
      id: 'y-auto', lane: 'system', col: 3,
      title: L('ຈັບຄູ່ອັດຕະໂນມັດ', 'Auto-match'),
      desc: L('ໝັ້ນໃຈສູງ → AUTO_MATCHED ແລະ ປິດຍອດທັນທີ.', 'High confidence → AUTO_MATCHED and settles immediately.'),
      statuses: ['AUTO_MATCHED'],
    },
    {
      id: 'a-review', lane: 'admin', col: 3,
      title: L('ຄົນກວດສະລິບ', 'Human Review'),
      desc: L('ຈອງ (claim) ກ່ອນກວດ, ຂໍຂໍ້ມູນເພີ່ມ, ອະນຸມັດຫຼາຍລາຍການ.', 'Claim lock, request info, bulk approve.'),
      apis: ['POST /payments-treasury/slips/:id/claim', 'POST /payments-treasury/slips/:id/review', 'POST /payments-treasury/slips/bulk-approve'],
      route: ROUTES.paymentsSlips,
      statuses: ['NEEDS_REVIEW', 'APPROVED', 'REJECTED'],
      permission: 'payments:review',
    },
    {
      id: 'a-reverse', lane: 'admin', col: 5,
      title: L('ກັບຄືນລາຍການ', 'Reverse'),
      desc: L('ອະນຸມັດຜິດ → REVERSED (ຍອດຊຳລະຖືກຫັກຄືນ).', 'Wrongly approved → REVERSED (payment rolled back).'),
      apis: ['POST /payments-treasury/slips/:id/reverse'],
      statuses: ['REVERSED'],
      permission: 'payments:review',
    },
    {
      id: 's-review', lane: 'staff', col: 4,
      title: L('ກວດໃນມືຖື', 'Mobile Review'),
      desc: L('ຜູ້ມີສິດກວດສະລິບຈາກແອັບ Staff ໄດ້.', 'Authorised staff can review from the Staff app.'),
      screen: 'StaffSlipReviewScreen',
    },
    {
      id: 'y-sla', lane: 'system', col: 4, row: 1,
      title: L('SLA ການກວດ', 'Review SLA'),
      desc: L('ສະລິບຄ້າງດົນ → ແຈ້ງເຕືອນ.', 'Slips waiting too long raise an alert.'),
      job: 'slip-sla.job · */5 * * * *',
    },
    {
      id: 'a-export', lane: 'admin', col: 6,
      title: L('ສົ່ງອອກ + ກະທົບຍອດ', 'Export + Reconcile'),
      desc: L('ສະລິບທີ່ອະນຸມັດ ໄປຈັບຄູ່ກັບ statement ທະນາຄານ.', 'Approved slips feed bank statement matching.'),
      apis: ['GET /payments-treasury/slips/export'],
      route: ROUTES.paymentsReconciliation,
      permission: 'payments:manage',
    },
  ],
  edges: [
    edge('c-upload', 'y-ocr', 'data'),
    edge('s-upload', 'y-ocr', 'data'),
    edge('y-ocr', 'y-risk', 'auto'),
    edge('y-risk', 'y-auto', 'status', L('ໝັ້ນໃຈສູງ', 'high confidence')),
    edge('y-risk', 'a-review', 'status', L('NEEDS_REVIEW', 'NEEDS_REVIEW')),
    edge('a-review', 's-review', 'data'),
    edge('y-sla', 'a-review', 'auto', L('ຄ້າງດົນ', 'overdue')),
    edge('a-review', 'a-reverse', 'status'),
    edge('y-auto', 'a-export', 'data'),
    edge('a-review', 'a-export', 'data', L('APPROVED', 'APPROVED')),
  ],
};

export const treasuryFlow: Flow = {
  id: 'treasury',
  group: 'module',
  title: L('ບັນຊີທະນາຄານ + ກະທົບຍອດ', 'Banks & Reconciliation'),
  summary: L('ບັນຊີຮັບເງິນ, ອະນຸມັດປ່ຽນບັນຊີ, ນຳເຂົ້າ statement, ຈັບຄູ່, ລັອກງວດ', 'Receiving accounts, payee-change approval, statement import, matching, period lock'),
  nodes: [
    {
      id: 'a-banks', lane: 'admin', col: 0,
      title: L('ບັນຊີທະນາຄານ', 'Bank Accounts'),
      desc: L('ບັນຊີຮັບເງິນຕໍ່ສາຂາ + QR ຂອງບັນຊີ.', 'Receiving accounts per branch + account QR.'),
      apis: ['GET /payments-treasury/bank-accounts', 'GET /payments-treasury/bank-accounts/insights'],
      route: ROUTES.paymentsBanks,
      permission: 'payments:manage',
    },
    {
      id: 'a-change', lane: 'admin', col: 1,
      title: L('ຂໍປ່ຽນບັນຊີ', 'Payee Change Request'),
      desc: L('ສ້າງ/ແກ້/ປ່ຽນ QR ຕ້ອງມີຜູ້ອະນຸມັດຄົນທີສອງ.', 'Create/update/QR change needs a second approver.'),
      apis: ['POST /payments-treasury/bank-accounts', 'POST /payments-treasury/bank-account-changes/:id/approve'],
      route: ROUTES.paymentsBanks,
      statuses: ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'],
      permission: 'payments:manage',
    },
    {
      id: 'x-statement', lane: 'external', col: 2,
      title: L('Statement ທະນາຄານ', 'Bank Statement'),
      desc: L('ໄຟລ໌ CSV/Excel ຈາກທະນາຄານ.', 'CSV/Excel export from the bank.'),
    },
    {
      id: 'a-import', lane: 'admin', col: 3,
      title: L('ນຳເຂົ້າ Statement', 'Import Statement'),
      desc: L('ແຍກແຖວ CREDIT/DEBIT; ປ້ອນດ້ວຍມືກໍ່ໄດ້.', 'Parses CREDIT/DEBIT lines; manual entry too.'),
      apis: ['POST /payments-treasury/reconciliation/imports', 'PUT /payments-treasury/reconciliation/statements'],
      route: ROUTES.paymentsReconciliation,
      statuses: ['MANUAL', 'IMPORT'],
      permission: 'payments:manage',
    },
    {
      id: 'y-match', lane: 'system', col: 4,
      title: L('ຈັບຄູ່ແຖວ', 'Line Matching'),
      desc: L('ຈັບຄູ່ແຖວ statement ກັບລາຍການຊຳລະ/ສະລິບ.', 'Pairs statement lines with payments/slips.'),
      apis: ['POST /payments-treasury/reconciliation/rematch', 'GET /payments-treasury/reconciliation/lines/:id/candidates'],
      statuses: ['UNMATCHED', 'MATCHED', 'IGNORED'],
    },
    {
      id: 'a-variance', lane: 'admin', col: 5,
      title: L('ແກ້ສ່ວນຕ່າງ', 'Resolve Variance'),
      desc: L('ລະບຸເຫດຜົນ: ຄ່າທຳນຽມ, ເວລາ, ບັນຊີຜິດ, ສະລິບບໍ່ບັນທຶກ...', 'Reason: bank fee, timing, wrong account, unbooked slip...'),
      apis: ['POST /payments-treasury/reconciliation/statements/:id/resolve', 'POST /payments-treasury/reconciliation/lines/:id/match'],
      route: ROUTES.paymentsReconciliation,
      statuses: ['BANK_FEE', 'TIMING', 'WRONG_ACCOUNT', 'UNBOOKED_SLIP', 'DATA_ENTRY'],
      permission: 'payments:manage',
    },
    {
      id: 'a-lock', lane: 'admin', col: 6,
      title: L('ລັອກງວດ', 'Lock Period'),
      desc: L('ກວດຄວາມພ້ອມກ່ອນ; ລັອກແລ້ວແກ້ລາຍການໃນງວດບໍ່ໄດ້.', 'Readiness check first; locked periods reject edits.'),
      apis: ['GET /payments-treasury/reconciliation/periods/readiness', 'POST /payments-treasury/reconciliation/periods'],
      route: ROUTES.paymentsReconciliation,
      permission: 'payments:manage',
    },
    {
      id: 'y-remind', lane: 'system', col: 5, row: 1,
      title: L('ເຕືອນກະທົບຍອດ', 'Recon Reminder'),
      desc: L('ທຸກເຊົ້າ 09:00 ເຕືອນມື້ທີ່ຍັງບໍ່ໄດ້ກະທົບຍອດ.', 'Daily 09:00 reminder for un-reconciled days.'),
      job: 'reconciliation-reminder.job · 0 9 * * *',
    },
    {
      id: 'y-unassigned', lane: 'system', col: 2, row: 1,
      title: L('ເງິນໂອນບໍ່ມີບັນຊີ', 'Unassigned Transfers'),
      desc: L('ການໂອນທີ່ບໍ່ຮູ້ບັນຊີຮັບ ລໍຖ້າກຳນົດ.', 'Transfers with no known receiving account wait for assignment.'),
      apis: ['GET /payments-treasury/unassigned-transfers', 'PATCH /payments-treasury/transactions/:id/bank-account'],
    },
  ],
  edges: [
    edge('a-banks', 'a-change', 'status'),
    edge('a-change', 'y-unassigned', 'data'),
    edge('x-statement', 'a-import', 'data'),
    edge('a-import', 'y-match', 'auto'),
    edge('y-unassigned', 'y-match', 'data'),
    edge('y-match', 'a-variance', 'status', L('UNMATCHED', 'UNMATCHED')),
    edge('a-variance', 'a-lock', 'status'),
    edge('y-remind', 'a-variance', 'auto'),
  ],
};

export const expensesFlow: Flow = {
  id: 'expenses',
  group: 'module',
  title: L('ລາຍຈ່າຍ ແລະ ງົບປະມານ', 'Expenses & Budgets'),
  summary: L('ຮ່າງ → ສົ່ງ → ອະນຸມັດ → ຈ່າຍ; OCR ໃບບິນ, ເງິນສົດຍ່ອຍ, ງົບ, P&L', 'Draft → submit → approve → pay; receipt OCR, petty cash, budgets, P&L'),
  nodes: [
    {
      id: 'a-draft', lane: 'admin', col: 0,
      title: L('ບັນທຶກລາຍຈ່າຍ', 'Record Expense'),
      desc: L('ໝວດ OPERATING/PAYROLL/INVENTORY; ຫຼາຍສະກຸນເງິນ (FX).', 'OPERATING/PAYROLL/INVENTORY; multi-currency (FX).'),
      apis: ['POST /expenses', 'POST /expenses/bulk'],
      route: ROUTES.paymentsExpenses,
      statuses: ['DRAFT'],
      permission: 'expenses:view',
    },
    {
      id: 'y-ocr', lane: 'system', col: 0, row: 1,
      title: L('OCR ໃບບິນ', 'Receipt OCR'),
      desc: L('ສະແກນໃບບິນ → ຕື່ມຂໍ້ມູນອັດຕະໂນມັດ.', 'Scan a receipt → auto-fill the form.'),
      apis: ['POST /expenses/receipt-scan'],
    },
    {
      id: 'y-recurring', lane: 'system', col: 1, row: 1,
      title: L('ລາຍຈ່າຍປະຈຳ', 'Recurring Expenses'),
      desc: L('ສ້າງລາຍຈ່າຍປະຈຳເດືອນອັດຕະໂນມັດ 06:00.', 'Auto-creates recurring expenses daily at 06:00.'),
      apis: ['GET /expenses/recurring'],
      job: 'recurring-expense.job · 0 6 * * *',
    },
    {
      id: 'a-submit', lane: 'admin', col: 1,
      title: L('ສົ່ງຂໍອະນຸມັດ', 'Submit'),
      desc: L('ກວດງົບ ແລະ ວົງເງິນອະນຸມັດ.', 'Checks budget and approval limit.'),
      apis: ['POST /expenses/:id/submit'],
      statuses: ['SUBMITTED'],
    },
    {
      id: 'a-approve', lane: 'admin', col: 2,
      title: L('ອະນຸມັດ / ປະຕິເສດ', 'Approve / Reject'),
      desc: L('ເກີນວົງເງິນ → ຕ້ອງຜູ້ມີສິດສູງກວ່າ.', 'Above the limit → needs a higher approver.'),
      apis: ['POST /expenses/:id/approve', 'POST /expenses/:id/reject'],
      route: ROUTES.paymentsExpenses,
      statuses: ['APPROVED', 'REJECTED'],
      permission: 'expenses:view',
    },
    {
      id: 'a-pay', lane: 'admin', col: 3,
      title: L('ຈ່າຍເງິນ', 'Pay'),
      desc: L('ຈ່າຍຈາກບັນຊີທະນາຄານ ຫຼື ເງິນສົດຍ່ອຍ.', 'Paid from a bank account or petty cash.'),
      apis: ['POST /expenses/:id/pay'],
      statuses: ['PAID'],
    },
    {
      id: 'a-petty', lane: 'admin', col: 3, row: 1,
      title: L('ເງິນສົດຍ່ອຍ', 'Petty Cash'),
      desc: L('ເຕີມ, ຖອນ, ນັບເງິນ; ບັນທຶກທຸກລາຍການ.', 'Top-up, withdraw, count; every entry recorded.'),
      apis: ['GET /expenses/cash-funds', 'POST /expenses/cash-funds/:id/movements', 'POST /expenses/cash-funds/:id/count'],
      statuses: ['TOPUP', 'WITHDRAW', 'EXPENSE', 'REVERSAL', 'COUNT'],
    },
    {
      id: 'a-void', lane: 'admin', col: 4, row: 1,
      title: L('ຍົກເລີກ (Void)', 'Void'),
      desc: L('ຍົກເລີກລາຍຈ່າຍທີ່ຈ່າຍແລ້ວ ພ້ອມລາຍການກັບຄືນ.', 'Voids a paid expense with a reversing entry.'),
      apis: ['POST /expenses/:id/void'],
      statuses: ['VOIDED'],
    },
    {
      id: 'y-pl', lane: 'system', col: 4,
      title: L('ງົບ + ກຳໄລ/ຂາດທຶນ', 'Budgets + P&L'),
      desc: L('ລາຍຮັບ − ຕົ້ນທຶນ (COGS) − ລາຍຈ່າຍ ຕໍ່ສາຂາ/ເດືອນ.', 'Revenue − COGS − expenses per branch/month.'),
      apis: ['GET /expenses/budgets', 'GET /expenses/profit-loss', 'GET /expenses/summary'],
    },
  ],
  edges: [
    edge('y-ocr', 'a-draft', 'auto'),
    edge('y-recurring', 'a-draft', 'auto'),
    edge('a-draft', 'a-submit', 'status', L('SUBMITTED', 'SUBMITTED')),
    edge('a-submit', 'a-approve', 'status'),
    edge('a-approve', 'a-pay', 'status', L('APPROVED', 'APPROVED')),
    edge('a-pay', 'a-petty', 'data', L('ເງິນສົດ', 'cash')),
    edge('a-pay', 'y-pl', 'data'),
    edge('a-pay', 'a-void', 'status'),
  ],
};

export const inventoryFlow: Flow = {
  id: 'inventory',
  group: 'module',
  title: L('ສາງ ແລະ ສິນຄ້າ', 'Inventory & Stock'),
  summary: L('ສັ່ງຊື້ → ຮັບ lot → ໃຊ້ FEFO → ໂອນສາຂາ → ປັບ/ນັບ → ledger + ມູນຄ່າ', 'PO → receive lots → FEFO use → transfers → adjust/count → ledger + valuation'),
  nodes: [
    {
      id: 'a-product', lane: 'admin', col: 0,
      title: L('ສິນຄ້າ + ຈຸດສັ່ງຊື້ຄືນ', 'Products + Reorder'),
      desc: L('ລະດັບສະຕັອກ, lot, ວັນໝົດອາຍຸ, ຈຸດສັ່ງຊື້ຄືນ.', 'Stock levels, lots, expiry, reorder points.'),
      apis: ['GET /products', 'GET /products/stats'],
      route: ROUTES.inventory,
      permission: 'inventory:view',
    },
    {
      id: 'a-po', lane: 'admin', col: 1,
      title: L('ໃບສັ່ງຊື້ (PO)', 'Purchase Order'),
      desc: L('DRAFT → (ອະນຸມັດຖ້າເກີນເກນ) → ORDERED → ຮັບບາງສ່ວນ/ຄົບ.', 'DRAFT → (approval above threshold) → ORDERED → partial/full receipt.'),
      apis: ['POST /purchase-orders', 'POST /purchase-orders/:id/receive'],
      route: ROUTES.inventoryPurchaseOrders,
      statuses: ['DRAFT', 'PENDING_APPROVAL', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'],
      permission: 'inventory:view',
    },
    {
      id: 'x-supplier', lane: 'external', col: 1,
      title: L('ຜູ້ສະໜອງ', 'Supplier'),
      desc: L('ລາຍຊື່ ແລະ ເງື່ອນໄຂຜູ້ສະໜອງ.', 'Supplier directory and terms.'),
      apis: ['GET /suppliers'],
      route: ROUTES.inventorySuppliers,
    },
    {
      id: 'y-receive', lane: 'system', col: 2,
      title: L('ຮັບເຂົ້າ + WAC', 'Receive + WAC'),
      desc: L('ສ້າງ lot ພ້ອມວັນໝົດອາຍຸ; ຄິດຕົ້ນທຶນສະເລ່ຍຖ່ວງນ້ຳໜັກ.', 'Creates lots with expiry; weighted-average cost.'),
      statuses: ['PURCHASE_IN'],
    },
    {
      id: 'y-consume', lane: 'system', col: 3,
      title: L('ໃຊ້ໃນບໍລິການ (FEFO)', 'Service Consumption'),
      desc: L('ຕັດຈາກ lot ທີ່ໝົດອາຍຸກ່ອນ; ຄິດ COGS + margin ບໍລິການ.', 'Deducts earliest-expiring lot; COGS + service margin.'),
      apis: ['GET /stock-movements/service-margin', 'GET /stock-movements/cogs-summary'],
      statuses: ['SERVICE_CONSUMED'],
    },
    {
      id: 'a-transfer', lane: 'admin', col: 3, row: 1,
      title: L('ໂອນລະຫວ່າງສາຂາ', 'Branch Transfer'),
      desc: L('DRAFT → IN_TRANSIT (TRANSFER_OUT) → COMPLETED (TRANSFER_IN).', 'DRAFT → IN_TRANSIT (TRANSFER_OUT) → COMPLETED (TRANSFER_IN).'),
      apis: ['POST /stock-transfers', 'POST /stock-transfers/:id/send', 'POST /stock-transfers/:id/receive'],
      route: ROUTES.inventoryTransfers,
      statuses: ['IN_TRANSIT', 'COMPLETED'],
      permission: 'inventory:view',
    },
    {
      id: 'a-adjust', lane: 'admin', col: 4,
      title: L('ປັບສະຕັອກ (Maker-Checker)', 'Adjustment (Maker-Checker)'),
      desc: L('ເສຍຫາຍ, ໝົດອາຍຸ, ເສຍ, ຕົວຢ່າງ...; ເກີນເກນ → ຕ້ອງອະນຸມັດ.', 'Damaged, expired, lost, sample...; above threshold needs approval.'),
      apis: ['POST /stock-movements/adjust', 'POST /stock-adjustments/:id/approve'],
      route: ROUTES.inventory,
      statuses: ['ADJUSTMENT_ADD', 'ADJUSTMENT_DEDUCT', 'PENDING', 'APPROVED'],
      permission: 'inventory:view',
    },
    {
      id: 'a-count', lane: 'admin', col: 5,
      title: L('ນັບສະຕັອກ', 'Stock Count'),
      desc: L('FULL / CYCLE / SPOT; ສ່ວນຕ່າງ → ລາຍການປັບເມື່ອ POSTED.', 'FULL / CYCLE / SPOT; variance posts adjustments.'),
      apis: ['POST /stock-counts', 'PATCH /stock-counts/:id/lines', 'POST /stock-counts/:id/approve'],
      route: ROUTES.inventoryCounts,
      statuses: ['COUNTING', 'PENDING_APPROVAL', 'POSTED'],
      permission: 'inventory:view',
    },
    {
      id: 'a-ledger', lane: 'admin', col: 6,
      title: L('ບັນຊີເຄື່ອນໄຫວ + ມູນຄ່າ', 'Ledger + Valuation'),
      desc: L('ທຸກການເຄື່ອນໄຫວມີຕົ້ນທຶນ; ມູນຄ່າສາງ, ການສູນເສຍ.', 'Every movement costed; valuation, shrinkage.'),
      apis: ['GET /stock-movements', 'GET /stock-movements/valuation', 'GET /stock-movements/shrinkage'],
      route: ROUTES.inventoryLedger,
      permission: 'inventory:view',
    },
    {
      id: 'y-expiry', lane: 'system', col: 5, row: 1,
      title: L('ເຕືອນ lot ໝົດອາຍຸ', 'Lot Expiry Alerts'),
      desc: L('ແຈ້ງທີ່ 60 → 30 → 7 ວັນ → ໝົດອາຍຸ; ເອີ້ນຄືນ lot ໄດ້.', 'Alerts at 60 → 30 → 7 days → expired; lot recall.'),
      job: 'lot-expiry.job · 30 8 * * *',
    },
    {
      id: 'y-recon', lane: 'system', col: 6, row: 1,
      title: L('ກວດຄວາມຖືກຕ້ອງຍາມຄືນ', 'Nightly Stock Check'),
      desc: L('SUM(ການເຄື່ອນໄຫວ) ຕ້ອງເທົ່າ stockQty; ບໍ່ກົງ → ແຈ້ງ SUPER_ADMIN.', 'SUM(movements) must equal stockQty; mismatch alerts SUPER_ADMIN.'),
      job: 'stock-reconciliation.job · 30 2 * * *',
    },
  ],
  edges: [
    edge('a-product', 'a-po', 'data', L('ຕ່ຳກວ່າຈຸດສັ່ງ', 'below reorder')),
    edge('a-po', 'x-supplier', 'data', L('ORDERED', 'ORDERED')),
    edge('x-supplier', 'y-receive', 'data', L('ສົ່ງເຄື່ອງ', 'deliver')),
    edge('y-receive', 'y-consume', 'data'),
    edge('y-receive', 'a-transfer', 'data'),
    edge('y-consume', 'a-adjust', 'data'),
    edge('a-adjust', 'a-count', 'data'),
    edge('a-count', 'a-ledger', 'status', L('POSTED', 'POSTED')),
    edge('a-transfer', 'a-ledger', 'data'),
    edge('y-expiry', 'a-adjust', 'auto', L('EXPIRED', 'EXPIRED')),
    edge('y-recon', 'a-ledger', 'auto'),
  ],
};
