import { ROUTES } from '@/router/paths';

import { edge, L, type Flow } from './systemMap.types';

export const rewardsFlow: Flow = {
  id: 'rewards',
  group: 'module',
  title: L('ແພັກເກັດ, ບັດຂອງຂວັນ, ແຕ້ມ, ແນະນຳ', 'Packages, Gift Cards, Loyalty, Referral'),
  summary: L('ສິນຄ້າທີ່ຈ່າຍລ່ວງໜ້າ ແລະ ລາງວັນ ທີ່ໃຊ້ເປັນວິທີຊຳລະໄດ້', 'Prepaid products and rewards that become payment tenders'),
  nodes: [
    {
      id: 'c-package', lane: 'customer', col: 0,
      title: L('ຊື້ແພັກເກັດ', 'Buy Package'),
      desc: L('ລາຄາຕໍ່ຄັ້ງ, % ປະຢັດ, ວັນໝົດອາຍຸ.', 'Per-session price, savings %, expiry.'),
      apis: ['GET /packages', 'POST /packages/:id/purchase'],
      screen: 'PackagesScreen → PackageCheckoutScreen',
      statuses: ['PENDING_PAYMENT'],
    },
    {
      id: 'c-gift', lane: 'customer', col: 0, row: 1,
      title: L('ຊື້ບັດຂອງຂວັນ', 'Buy Gift Card'),
      desc: L('ຊື້ໃຫ້ຕົນເອງ ຫຼື ຄົນອື່ນ.', 'For yourself or someone else.'),
      apis: ['POST /gift-cards/purchase', 'GET /gift-cards/me'],
      screen: 'GiftCardCheckoutScreen',
    },
    {
      id: 'y-activate', lane: 'system', col: 1,
      title: L('ເປີດໃຊ້ຫຼັງຈ່າຍ', 'Activate on Payment'),
      desc: L('ຊຳລະຄົບ → ACTIVE; ຍົກເລີກ → VOID.', 'Paid → ACTIVE; cancelled → VOID.'),
      statuses: ['ACTIVE', 'VOID'],
    },
    {
      id: 'c-mine', lane: 'customer', col: 2,
      title: L('ແພັກເກັດຂອງຂ້ອຍ', 'My Packages'),
      desc: L('ຄັ້ງທີ່ເຫຼືອ, ມື້ທີ່ເຫຼືອ, ປະຫວັດການໃຊ້.', 'Sessions left, days left, usage history.'),
      apis: ['GET /packages/me', 'GET /packages/me/:id/usage'],
      screen: 'MyPackagesScreen',
    },
    {
      id: 'y-redeem', lane: 'system', col: 3,
      title: L('ໃຊ້ເປັນວິທີຈ່າຍ', 'Redeem as Tender'),
      desc: L('PACKAGE_CREDIT / GIFT_CARD / LOYALTY_POINTS ຕອນຮັບຊຳລະ.', 'PACKAGE_CREDIT / GIFT_CARD / LOYALTY_POINTS at checkout.'),
      apis: ['POST /payments/:id/tenders', 'GET /gift-cards/lookup'],
      statuses: ['PACKAGE_CREDIT', 'GIFT_CARD', 'LOYALTY_POINTS', 'DEPLETED'],
    },
    {
      id: 'y-earn', lane: 'system', col: 4,
      title: L('ສະສົມແຕ້ມ + ລະດັບ', 'Earn + Tier'),
      desc: L('EARN ຈາກຍອດຈ່າຍ; SILVER → GOLD → PLATINUM; ແຕ້ມໝົດອາຍຸ.', 'EARN from spend; SILVER → GOLD → PLATINUM; points expire.'),
      statuses: ['EARN', 'REDEEM', 'EXPIRE', 'SILVER', 'GOLD', 'PLATINUM'],
    },
    {
      id: 'c-loyalty', lane: 'customer', col: 5,
      title: L('ບັດສະມາຊິກ', 'Loyalty Card'),
      desc: L('ແຕ້ມ, ລະດັບ, ຄວາມຄືບໜ້າ ໄປລະດັບຕໍ່ໄປ.', 'Points, tier, progress to next tier.'),
      apis: ['GET /loyalty/me', 'GET /loyalty/me/ledger'],
      screen: 'LoyaltyScreen',
    },
    {
      id: 'c-referral', lane: 'customer', col: 4, row: 1,
      title: L('ແນະນຳໝູ່', 'Refer a Friend'),
      desc: L('ລະຫັດແນະນຳ; ລາງວັນເມື່ອໝູ່ຈອງຄັ້ງທຳອິດ.', 'Referral code; reward when a friend first books.'),
      apis: ['GET /referral/me', 'GET /referral/me/usages'],
      screen: 'ReferralScreen',
    },
    {
      id: 'a-packages', lane: 'admin', col: 1, row: 1,
      title: L('ບັດຂອງຂວັນ (ແອັດມິນ)', 'Gift Cards (Admin)'),
      desc: L('ອອກບັດ, ຕິດຕາມມູນຄ່າທີ່ເຫຼືອ.', 'Issue cards, track remaining value.'),
      apis: ['POST /gift-cards/issue', 'GET /gift-cards'],
      route: ROUTES.giftCards,
      permission: 'finance:view',
    },
    {
      id: 'a-loyalty', lane: 'admin', col: 5, row: 1,
      title: L('ບັນຊີແຕ້ມ', 'Loyalty Ledger'),
      desc: L('ປັບແຕ້ມດ້ວຍມື (ADJUST) ພ້ອມເຫດຜົນ.', 'Manual ADJUST with reason.'),
      apis: ['GET /loyalty/accounts', 'POST /loyalty/accounts/:userId/adjust'],
      route: ROUTES.loyalty,
      permission: 'finance:view',
    },
    {
      id: 'a-referrals', lane: 'admin', col: 6,
      title: L('ພາກສ່ວນແນະນຳ + ຈ່າຍ', 'Affiliates + Payouts'),
      desc: L('PENDING → PROCESSING → PAID / REJECTED.', 'PENDING → PROCESSING → PAID / REJECTED.'),
      apis: ['GET /affiliates', 'POST /affiliates/:id/payouts', 'PATCH /affiliates/payouts/:id'],
      route: ROUTES.referrals,
      statuses: ['PENDING', 'PROCESSING', 'PAID', 'REJECTED'],
      permission: 'finance:view',
    },
  ],
  edges: [
    edge('c-package', 'y-activate', 'status', L('ຈ່າຍແລ້ວ', 'paid')),
    edge('c-gift', 'y-activate', 'status'),
    edge('a-packages', 'y-activate', 'data'),
    edge('y-activate', 'c-mine', 'data'),
    edge('c-mine', 'y-redeem', 'data', L('ຈອງ/ໃຊ້', 'book/use')),
    edge('y-redeem', 'y-earn', 'auto'),
    edge('y-earn', 'c-loyalty', 'data'),
    edge('a-loyalty', 'c-loyalty', 'data', L('ADJUST', 'ADJUST')),
    edge('c-referral', 'a-referrals', 'auto', L('ໝູ່ຈອງ', 'friend booked')),
  ],
};

export const marketingFlow: Flow = {
  id: 'marketing',
  group: 'module',
  title: L('ການຕະຫຼາດ ແລະ ແຈ້ງເຕືອນ', 'Marketing & Notifications'),
  summary: L('ແຄມເປນອັດຕະໂນມັດ, ການຍິນຍອມ, ລາຍຊື່ຫ້າມສົ່ງ, ກ່ອງແຈ້ງເຕືອນ', 'Automated campaigns, consent, suppression list, notification inbox'),
  nodes: [
    {
      id: 'a-campaign', lane: 'admin', col: 0,
      title: L('ສ້າງແຄມເປນ', 'Create Campaign'),
      desc: L('BIRTHDAY / WIN_BACK / FESTIVAL_PROMO / CUSTOM + ຕົວຢ່າງຂໍ້ຄວາມ.', 'BIRTHDAY / WIN_BACK / FESTIVAL_PROMO / CUSTOM + live preview.'),
      apis: ['POST /marketing/campaigns', 'GET /marketing/campaigns/:id/recipients'],
      route: ROUTES.marketing,
      statuses: ['BIRTHDAY', 'WIN_BACK', 'FESTIVAL_PROMO', 'CUSTOM'],
      permission: 'marketing:view',
    },
    {
      id: 'a-pricing', lane: 'admin', col: 0, row: 1,
      title: L('ລາຄາຕາມເວລາ + ໂປຣ', 'Dynamic Pricing + Promos'),
      desc: L('ກົດລາຄາຕາມຊ່ວງເວລາ (ເວລາ Vientiane).', 'Time-band price rules (Vientiane time).'),
      apis: ['GET /pricing-rules', 'POST /pricing-rules'],
      route: ROUTES.pricing,
      permission: 'finance:view',
    },
    {
      id: 'y-sweep', lane: 'system', col: 1,
      title: L('ແຄມເປນປະຈຳວັນ', 'Daily Campaign Sweep'),
      desc: L('08:00 ທຸກມື້ ຣັນແຄມເປນທີ່ active; ກັນສົ່ງຊ້ຳດ້ວຍ dedupeKey.', 'Runs active campaigns daily at 08:00; dedupeKey prevents repeats.'),
      apis: ['POST /marketing/campaigns/:id/run'],
      job: 'marketing.job · 0 8 * * *',
    },
    {
      id: 'y-consent', lane: 'system', col: 2,
      title: L('ກວດການຍິນຍອມ', 'Consent Filter'),
      desc: L('ສົ່ງສະເພາະຊ່ອງທາງທີ່ຍິນຍອມ; ຕັດຄົນໃນລາຍຊື່ຫ້າມສົ່ງ.', 'Only consented channels; suppressed contacts removed.'),
      apis: ['GET /marketing/consent-summary', 'GET /marketing/suppressions'],
      statuses: ['PUSH', 'SMS', 'EMAIL', 'LINE'],
    },
    {
      id: 'x-channels', lane: 'external', col: 3,
      title: L('Push / SMS / LINE / Email', 'Push / SMS / LINE / Email'),
      desc: L('Adapter ຕໍ່ຊ່ອງທາງ; ຮັບ inbound STOP ແລະ webhook.', 'Per-channel adapters; inbound STOP and webhooks.'),
      apis: ['POST /consent/sms/inbound', 'POST /consent/line/webhook'],
    },
    {
      id: 'c-inbox', lane: 'customer', col: 4,
      title: L('ແຈ້ງເຕືອນໃນແອັບ', 'In-app Notifications'),
      desc: L('ລາຍການແຈ້ງເຕືອນ + ຕັ້ງຄ່າການຮັບ.', 'Notification list + delivery preferences.'),
      apis: ['GET /consent/me', 'PUT /consent/me'],
      screen: 'NotificationsScreen · NotificationPreferencesScreen',
    },
    {
      id: 'c-unsub', lane: 'customer', col: 5,
      title: L('ຍົກເລີກການຮັບ', 'Unsubscribe'),
      desc: L('ລິ້ງ/STOP → ເພີ່ມເຂົ້າລາຍຊື່ຫ້າມສົ່ງ (UNSUBSCRIBE).', 'Link/STOP → suppression (UNSUBSCRIBE).'),
      apis: ['POST /consent/unsubscribe'],
      statuses: ['UNSUBSCRIBE', 'BOUNCE', 'COMPLAINT'],
    },
    {
      id: 'a-inbox', lane: 'admin', col: 4, row: 1,
      title: L('ກ່ອງແຈ້ງເຕືອນແອັດມິນ', 'Admin Notification Inbox'),
      desc: L('ລະດັບຄວາມຮຸນແຮງ, ໝາຍວ່າແກ້ແລ້ວ, ອ່ານທັງໝົດ.', 'Severity, resolve, mark all read.'),
      apis: ['GET /notifications', 'GET /notifications/unread-count', 'POST /notifications/read-all'],
      route: ROUTES.notifications,
    },
    {
      id: 'a-templates', lane: 'admin', col: 1, row: 1,
      title: L('ແມ່ແບບຂໍ້ຄວາມ', 'Message Templates'),
      desc: L('ແມ່ແບບແຈ້ງເຕືອນ ແລະ ເວລາເຕືອນນັດ.', 'Notification templates and reminder timing.'),
      apis: ['GET /notification-templates', 'PUT /notification-templates/:key'],
      route: ROUTES.settingsNotifications,
      permission: 'settings:view',
    },
  ],
  edges: [
    edge('a-campaign', 'y-sweep', 'data'),
    edge('a-templates', 'y-sweep', 'data'),
    edge('y-sweep', 'y-consent', 'auto'),
    edge('y-consent', 'x-channels', 'auto'),
    edge('x-channels', 'c-inbox', 'data'),
    edge('c-inbox', 'c-unsub', 'status'),
    edge('c-unsub', 'y-consent', 'status', L('suppression', 'suppression')),
    edge('y-consent', 'a-inbox', 'auto', L('ສົ່ງບໍ່ສຳເລັດ', 'delivery failures')),
    edge('a-pricing', 'a-campaign', 'data', L('ໂປຣ', 'promo')),
  ],
};

export const messagingFlow: Flow = {
  id: 'messaging',
  group: 'module',
  title: L('ແຊັດ ແລະ ຂໍ້ຄວາມ', 'Chat & Messaging'),
  summary: L('ແຊັດຕາມນັດ, ຂໍ້ຄວາມໂດຍກົງ, ຮູບ/ສຽງ, ລາຍງານ/ບລັອກ, Telegram bot', 'Appointment chat, direct messages, media, report/block, Telegram bot'),
  nodes: [
    {
      id: 'c-chat', lane: 'customer', col: 0,
      title: L('ແຊັດປຶກສາ', 'Consultation Chat'),
      desc: L('ຫ້ອງແຊັດຜູກກັບນັດ; ຂໍ້ຄວາມ, ຮູບ, ກ້ອງ, ສຽງ.', 'Thread per appointment; text, image, camera, voice.'),
      apis: ['POST /chat/appointments/:appointmentId/thread', 'POST /chat/threads/:id/messages', 'POST /chat/threads/:id/media'],
      screen: 'ChatScreen',
      statuses: ['CONSULTATION'],
    },
    {
      id: 'c-dm', lane: 'customer', col: 0, row: 1,
      title: L('ຂໍ້ຄວາມໂດຍກົງ', 'Direct Messages'),
      desc: L('ກ່ອງຂໍ້ຄວາມ, ຍັງບໍ່ອ່ານ, ບລັອກ/ປົດບລັອກ.', 'Inbox, unread, block/unblock.'),
      apis: ['GET /conversations', 'POST /conversations/:id/read', 'POST /conversations/block/:userId'],
      screen: 'DirectMessagesScreen · DirectThreadScreen',
      statuses: ['DIRECT'],
    },
    {
      id: 'y-socket', lane: 'system', col: 1,
      title: L('Realtime (socket.io)', 'Realtime (socket.io)'),
      desc: L('ສົ່ງຂໍ້ຄວາມທັນທີ; lastReadAt ສຳລັບສະຖານະອ່ານ.', 'Instant delivery; lastReadAt for read receipts.'),
    },
    {
      id: 'a-inbox', lane: 'admin', col: 2,
      title: L('ກ່ອງຂໍ້ຄວາມ 3 ແຖບ', '3-pane Inbox'),
      desc: L('ພະນັກງານຕອບລູກຄ້າ, ລັອກຫ້ອງ, ເບິ່ງສື່.', 'Staff reply, lock thread, view media.'),
      apis: ['GET /conversations', 'PATCH /conversations/:id/lock', 'GET /conversations/:id/media'],
      route: ROUTES.messaging,
      permission: 'queue:manage',
    },
    {
      id: 's-threads', lane: 'staff', col: 2,
      title: L('ແຊັດໃນແອັບ Staff', 'Staff App Threads'),
      desc: L('ລວມ STAFF_INTERNAL ລະຫວ່າງພະນັກງານ.', 'Includes STAFF_INTERNAL between staff.'),
      screen: 'ConversationListScreen · StaffThreadScreen',
      statuses: ['STAFF_INTERNAL'],
    },
    {
      id: 'c-report', lane: 'customer', col: 3,
      title: L('ລາຍງານຂໍ້ຄວາມ', 'Report Message'),
      desc: L('ລາຍງານເນື້ອຫາບໍ່ເໝາະສົມ.', 'Report inappropriate content.'),
      apis: ['POST /conversations/:id/report'],
    },
    {
      id: 'a-moderation', lane: 'admin', col: 4,
      title: L('ກວດລາຍງານແຊັດ', 'Chat Moderation'),
      desc: L('ພິຈາລະນາລາຍງານ ແລະ ຜູ້ໃຊ້ທີ່ຖືກບລັອກ.', 'Review reports and blocked users.'),
      apis: ['GET /conversations/reports', 'PATCH /conversations/reports/:id'],
      route: ROUTES.chatModeration,
      permission: 'settings:view',
    },
    {
      id: 'y-lock', lane: 'system', col: 3, row: 1,
      title: L('ລັອກແຊັດອັດຕະໂນມັດ', 'Auto-lock Threads'),
      desc: L('03:00 ທຸກມື້ ລັອກຫ້ອງປຶກສາທີ່ໝົດອາຍຸ (ອ່ານໄດ້ ສົ່ງບໍ່ໄດ້).', 'Daily 03:00 locks expired consultations (read-only).'),
      job: 'chat-lock.job · 0 3 * * *',
    },
    {
      id: 'x-telegram', lane: 'external', col: 1,
      title: L('Telegram Bot', 'Telegram Bot'),
      desc: L('ເຊື່ອມບັນຊີດ້ວຍລະຫັດ; ຮັບແຈ້ງເຕືອນຜ່ານ Telegram.', 'Link with a code; receive notifications on Telegram.'),
      apis: ['POST /chatbot/telegram/link-code', 'POST /chatbot/telegram/webhook'],
    },
  ],
  edges: [
    edge('c-chat', 'y-socket', 'data'),
    edge('c-dm', 'y-socket', 'data'),
    edge('y-socket', 'a-inbox', 'data'),
    edge('y-socket', 's-threads', 'data'),
    edge('x-telegram', 'y-socket', 'data'),
    edge('c-chat', 'c-report', 'data'),
    edge('c-report', 'a-moderation', 'data'),
    edge('y-lock', 'a-inbox', 'auto', L('ລັອກ', 'lock')),
  ],
};

export const adminFlow: Flow = {
  id: 'admin',
  group: 'module',
  title: L('ລາຍງານ ແລະ ການຕັ້ງຄ່າ', 'Reports & Settings'),
  summary: L('ຂໍ້ມູນຫຼັກ, ການຕັ້ງຄ່າ, ໂມດູນ, ລາຍງານ, ນຳເຂົ້າ/ສົ່ງອອກ, audit', 'Master data, settings, modules, reports, import/export, audit'),
  nodes: [
    {
      id: 'a-branches', lane: 'admin', col: 0,
      title: L('ສາຂາ + ວັນປິດ', 'Branches + Closures'),
      desc: L('ເວລາເປີດ, ວັນປິດ, QR ເຊັກອິນ.', 'Opening hours, closures, check-in QR.'),
      apis: ['GET /branches', 'POST /branch-closures'],
      route: ROUTES.branches,
      permission: 'branches:view',
    },
    {
      id: 'a-services', lane: 'admin', col: 1,
      title: L('ບໍລິການ + ໝວດ', 'Services + Categories'),
      desc: L('ລາຄາ, ໄລຍະເວລາ, ວັດຖຸທີ່ໃຊ້, ຫ້ອງ/ອຸປະກອນທີ່ຕ້ອງການ.', 'Price, duration, consumables, required room/equipment.'),
      apis: ['GET /services', 'POST /services', 'GET /service-categories'],
      route: ROUTES.services,
      permission: 'services:view',
    },
    {
      id: 'a-customers', lane: 'admin', col: 2,
      title: L('ລູກຄ້າ', 'Customers'),
      desc: L('ໂປຣໄຟລ໌, ປະຫວັດການມາ, ບັນທຶກ, ການຍິນຍອມ.', 'Profile, visit history, notes, consent.'),
      apis: ['GET /customers', 'GET /customers/:id', 'PATCH /customers/:id'],
      route: ROUTES.customers,
      permission: 'customers:view',
    },
    {
      id: 'a-settings', lane: 'admin', col: 0, row: 1,
      title: L('ການຕັ້ງຄ່າລະບົບ', 'System Settings'),
      desc: L('ຂໍ້ມູນຄລີນິກ, ຮູບແບບ, ກົດການຈອງ, ນະໂຍບາຍຍົກເລີກ.', 'Clinic profile, appearance, booking rules, cancel policy.'),
      apis: ['GET /settings', 'PUT /settings'],
      route: ROUTES.settings,
      permission: 'settings:view',
    },
    {
      id: 'a-modules', lane: 'admin', col: 1, row: 1,
      title: L('ຈັດການໂມດູນ', 'Module Management'),
      desc: L('ສະແດງ/ເຊື່ອງ ແລະ ຈັດລຳດັບເມນູ.', 'Show/hide and reorder sidebar modules.'),
      route: ROUTES.settingsModules,
      permission: 'settings:view',
    },
    {
      id: 'y-stats', lane: 'system', col: 3,
      title: L('ລວມສະຖິຕິ', 'Stats Aggregation'),
      desc: L('ລວມຕາມວັນ Vientiane; ຈຳກັດຕາມສາຂາຂອງ BRANCH_ADMIN.', 'Aggregated per Vientiane day; scoped to BRANCH_ADMIN branch.'),
      apis: ['GET /dashboard/stats', 'GET /appointments/summary'],
    },
    {
      id: 'a-dashboard', lane: 'admin', col: 4,
      title: L('ແດຊບອດ', 'Dashboard'),
      desc: L('ລາຍຮັບ, ເລື່ອງທີ່ຕ້ອງເອົາໃຈໃສ່, ຄະແນນ, ສະຕັອກ.', 'Revenue, attention items, rating, stock.'),
      route: ROUTES.dashboard,
      permission: 'dashboard:view',
    },
    {
      id: 'a-reports', lane: 'admin', col: 5,
      title: L('ລາຍງານປິດມື້', 'End-of-day Reports'),
      desc: L('ລາຍງານແບບ statement / ledger.', 'Statement / ledger-style reports.'),
      apis: ['GET /reports', 'GET /reports/end-of-day'],
      route: ROUTES.reports,
      permission: 'reports:view',
    },
    {
      id: 'a-io', lane: 'admin', col: 5, row: 1,
      title: L('ນຳເຂົ້າ / ສົ່ງອອກ', 'Import / Export'),
      desc: L('ນຳເຂົ້າ ແລະ ສົ່ງອອກຂໍ້ມູນເປັນຊຸດ.', 'Bulk data import and export.'),
      route: ROUTES.importExport,
      permission: 'reports:view',
    },
    {
      id: 'y-audit', lane: 'system', col: 2, row: 1,
      title: L('Audit Log', 'Audit Log'),
      desc: L('middleware ບັນທຶກທຸກການປ່ຽນແປງ.', 'Middleware records every mutation.'),
      apis: ['GET /audit-logs'],
      route: ROUTES.auditLog,
      permission: 'settings:view',
    },
  ],
  edges: [
    edge('a-branches', 'a-services', 'data'),
    edge('a-services', 'a-customers', 'data'),
    edge('a-customers', 'y-stats', 'data'),
    edge('y-stats', 'a-dashboard', 'data'),
    edge('a-dashboard', 'a-reports', 'data'),
    edge('a-reports', 'a-io', 'data'),
    edge('a-settings', 'a-modules', 'data'),
    edge('a-settings', 'y-audit', 'auto'),
    edge('a-modules', 'y-audit', 'auto'),
  ],
};
